### ISSUE TITLE
Error: ENOENT: no such file or directory, open /proc/<pid?>/fd/pipe:[number]

### ISSUE THREAD

**Issue by CaelumF** [mikehearn/nodejs-interop#3]
Hi,

This project is so cool!

When I try to run it, I get this:

```
build/nodejvm/nodejvm -cp "build/libs/*.jar" net.plan99.NodeJS.Demo                                                                                                                                                                                         [10:48:19]
'--jvm.*' options are deprecated, use '--vm.*' instead.
fs.js:443
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/proc/31134/fd/pipe:[1627155]'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (internal/modules/cjs/loader.js:788:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function._load (internal/modules/cjs/loader.js:585:3)
    at Function.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:296:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:635:3)

```

Running from Fedora 30. Any thoughts?

**Comment by mikehearn** [comment]
What version of GraalVM are you using? Looks like it's regressed somehow.

Is that running in some sort of container?

**Comment by CaelumF** [comment]
I see you made some changes, cool! like the wiki theme.

Here is a more comprehensive list of the steps I took:
`git clone https://github.com/mikehearn/nodejvm/`
`cd nodejvm`
`gradle build`
`cd dat-sample`
`gradle build`
`mv build/libs/dat-sample-1.0.jar ../build/libs/dat-sample-1.0.jar`
`cd ..`

and then lastly:
```
GRAALVM_PATH=/home/$USER/rice/graalvm-ce-19.2.1/bin build/nodejvm/nodejvm -cp "build/libs/*.jar" net.plan99.nodejs.sample
fs.js:443
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/proc/28682/fd/pipe:[4857201]'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (internal/modules/cjs/loader.js:788:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function._load (internal/modules/cjs/loader.js:585:3)
    at Function.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:296:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:635:3)

```

I tried using an older Graalvm from around when the earlier commits to this repo were, also:
```
 GRAALVM_PATH=/home/$USER/rice/graalvm-ce-1.0.0-rc12/bin/ build/nodejvm/nodejvm -cp "build/libs/*.jar" net.plan99.nodejs.sample
ERROR: Unrecognized argument: '--vm.cp=/home/$USER/IdeaProjects/nodejvm/build/nodejvm/nodejs-interop-1.0.jar:build/libs/dat-sample-1.0.jar'. Use --help for usage instructions.
```

I actually remember it giving the same error as before, unlike it's giving now ^, but I could be wrong. Perhaps rc12 doesn't work after the recent changes

For good measure, also I'll try rc16:

```
$ GRAALVM_PATH=/home/$USER/rice/graalvm-ce-1.0.0-rc16/bin/ build/nodejvm/nodejvm -cp "build/libs/*.jar" net.plan99.nodejs.sample                                                                                                                                                                                           [16:36:32]
fs.js:439
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/proc/27995/fd/pipe:[4847803]'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.<anonymous> (internal/modules/cjs/loader.js:699:20)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function._load (internal/modules/cjs/loader.js:530:3)
    at Function.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:296:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:756:3)
```

Not running inside of a container, perhaps I'd have better luck doing that.

**Comment by mikehearn** [comment]
I wonder if it's related to the use of *.jar in your classpath.

If you change the double to single quotes, does that make any difference?

**Comment by mikehearn** [comment]
By the way, this is an easier way to run things:

`gradle dat-sample:run`

Does that work for you? If on master please re-pull as I've fixed some bugs.

**Comment by mikehearn** [comment]
Never mind - I figured out what your problem is. I'll work on a fix. I suspect you're using a different OS or shell to me, which interacts badly with the way I pipe the boot script to Node.

**Comment by mikehearn** [comment]
You should be able to get further now. Take a look at the updated instructions page and see if it helps:

https://mikehearn.github.io/nodejvm/running-polyglot-programs/
